"""Generate browser emoji shortcode data from GitHub gemoji.

Source: https://github.com/github/gemoji/blob/master/db/emoji.json
"""

from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path


SOURCE_URL = "https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json"
OUT_PATH = Path("static/js/emojiShortcodes.js")


def _key(value: str) -> str:
    normalized = value.strip().lower()
    if re.fullmatch(r"[+-]\d+", normalized):
        return normalized
    return re.sub(r"\s+", " ", re.sub(r"[_-]+", " ", normalized)).strip()


def _add(mapping: dict[str, str], key: str, emoji: str) -> None:
    clean_key = _key(key)
    if not clean_key or not emoji:
        return
    mapping.setdefault(clean_key, emoji)


def main() -> int:
    with urllib.request.urlopen(SOURCE_URL, timeout=30) as response:
        entries = json.loads(response.read().decode("utf-8"))

    mapping: dict[str, str] = {}
    for entry in entries:
        emoji = entry.get("emoji") or ""
        if not emoji:
            continue
        for alias in entry.get("aliases") or []:
            _add(mapping, alias, emoji)
        description = entry.get("description") or ""
        _add(mapping, description, emoji)
        for tag in entry.get("tags") or []:
            _add(mapping, tag, emoji)

    # Common model wording that is not a gemoji alias/tag.
    _add(mapping, "ok", "\U0001f44c")
    _add(mapping, "thumbs up", "\U0001f44d")
    _add(mapping, "thumbs down", "\U0001f44e")

    lines = [
        "// Generated by scripts/generate_emoji_shortcodes.py from GitHub gemoji.",
        f"// Source: {SOURCE_URL}",
        "const EMOJI_SHORTCODES = Object.freeze({",
    ]
    for key in sorted(mapping):
        lines.append(f"  {json.dumps(key, ensure_ascii=False)}: {json.dumps(mapping[key], ensure_ascii=False)},")
    lines.extend(["});", "", "export default EMOJI_SHORTCODES;", ""])

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_PATH} with {len(mapping)} shortcodes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
